#!/bin/sh

start() {
	# Start daemons.
	echo -n "Starting ui: "
	modprobe emce
	cd /opt/emce; /usr/bin/python /usr/bin/twistd -y server.py; cd -
	echo "done"
}

stop() {
	# Stop daemons.
	echo "Shutting down ui: "
	/bin/kill `cat /opt/emce/twistd.pid`	
	echo "done"
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo "Usage: ui {start|stop|reload}"
	exit 1
esac

exit 0
